name: test code

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          [
            19.x,
            18.x,
            17.x,
            16.x,
            15.x,
            14.x,
            12.x,
            11.x,
            10.x,
            9.x,
            8.x,
            7.x,
            6.x,
          ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
